# Generated by Django 4.0.6 on 2022-09-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('brand', models.CharField(choices=[('Perfume', 'Perfume'), ('Cosmetics', 'Cosmetics')], max_length=100)),
                ('category', models.CharField(choices=[('Perfume', 'Perfume'), ('Cosmetics', 'Cosmetics')], max_length=100)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.FloatField()),
                ('is_displayed', models.BooleanField(default=True)),
                ('has_discount', models.BooleanField(default=False)),
                ('discount', models.FloatField()),
                ('photo', models.ImageField(upload_to='photos/spares')),
            ],
            options={
                'verbose_name': 'inventory',
                'verbose_name_plural': 'inventories',
            },
        ),
    ]
