# Generated by Django 4.0.6 on 2022-07-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='category',
            field=models.CharField(choices=[('Perfume', 'Perfume'), ('Cosmetics', 'Cosmetics')], max_length=100),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='has_discount',
            field=models.BooleanField(default=False),
        ),
    ]
