# Generated by Django 4.0.6 on 2022-07-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0002_alter_inventory_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='photo',
            field=models.ImageField(default=1, upload_to='photos/spares'),
            preserve_default=False,
        ),
    ]
