# Generated by Django 4.0.6 on 2022-09-08 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0002_brand_category_alter_inventory_brand_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'inventory', 'verbose_name_plural': 'inventory'},
        ),
    ]
