# Generated by Django 4.0.6 on 2022-09-08 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0002_cart_is_ordered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='items',
            new_name='item',
        ),
    ]
