# Generated by Django 4.0.6 on 2022-09-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0003_rename_items_cart_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
