# Generated by Django 4.0.6 on 2022-09-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0004_alter_inventory_brand_alter_inventory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='discount',
            field=models.FloatField(default=0),
        ),
    ]
