# Generated by Django 4.0.6 on 2022-09-12 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spares', '0005_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_fee',
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('shipping_location', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='spares.shipping'),
            preserve_default=False,
        ),
    ]
