# Generated by Django 4.0.6 on 2022-09-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0006_remove_order_shipping_fee_shipping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='description',
            field=models.TextField(default='denso iridium spark plugs'),
            preserve_default=False,
        ),
    ]
